# Generated by Django 4.1.2 on 2023-01-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_burger_bur_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='bur_price',
            field=models.IntegerField(default=''),
        ),
    ]
