# Generated by Django 4.1.2 on 2023-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_alter_burger_bur_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='at',
            field=models.IntegerField(default=0),
        ),
    ]
